version: '3'
services:
  angular:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: obugs-frontend

    container_name: obugs-frontend
    restart: always

    ports:
      - "19997:80"
    environment:
      - NGINX_HOST=obugs.the-cluster.org
      - NGINX_PORT=80
